# Generated by Django 2.0 on 2019-08-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verification',
            table='verification',
        ),
    ]
